### ISSUE TITLE
Update release on PyPi

### ISSUE THREAD

**Issue by pllim** [spacetelescope/spherical_geometry#102]
https://pypi.python.org/pypi/spherical-geometry is currently pointing to 1.0.6 even though 1.0.10 was released on GitHub (and AstroConda). The text needs to be updated too.

As a result of outdated PyPi, Astropy's conda channel is picking up the old version. See astropy/conda-channel-astropy#155

**Comment by bernie-simon** [comment]
I've uploaded a new version of spherical_geometry, 1.0.11, to PyPi.
