### ISSUE TITLE
Rename this repository "spherical_geometry"

### ISSUE THREAD

**Issue by pllim** [spacetelescope/spherical_geometry#104]
This is to be more consistent with the actual import name (`spherical_geometry`) and PyPi name (`spherical-geometry`). This will also allow astroconda/astroconda-contrib#235 to be resolved.

Any objection? 

FYI -- `sphere` is already taken by someone else on PyPi.

**Comment by bernie-simon** [comment]
Not from me.

**Comment by mcara** [comment]
``spherical_geometry`` sounds more descriptive than ``sphere``. 👍 for renaming.

**Comment by pllim** [comment]
Done. Thanks!
