### ISSUE TITLE
[ENH] Testing: Clean up Travis YML

### ISSUE THREAD

**Issue by pllim** [spacetelescope/spherical_geometry#111]
Travis CI set up can be cleaner. See https://github.com/astropy/package-template/blob/cookiecutter/.travis.yml as example.

**Comment by bernie-simon** [comment]
I removed the code that forced an older version of numpy, as it is no longer needed. I looked at the astropy template. Most of it assumes you use the cookiecutter template generator, which we are not using.

**Comment by pllim** [comment]
I was thinking more like `ci-helper` that allows `numpy=stable` specification and such, but no matter.
