### ISSUE TITLE
setup.cfg URL points to stone-age (2014) STSCI page?

### ISSUE THREAD

**Issue by michaelaye** [spacetelescope/spherical_geometry#121]
Found via pypi, the url in setup.cfg, as shown here:

https://pypi.python.org/pypi/spherical-geometry

points to the old STSCI python env from 2014:

http://www.stsci.edu/institute/software_hardware/pyraf/stsci_python

and that page does not mention spherical-geometry at all, so it's a tad confusing.

**Comment by pllim** [comment]
To be fair, 2014 was more like bronze age, but I can confirm that the link is still similarly problematic in `setup.cfg` in `master`. Thanks for reporting this!
