### ISSUE TITLE
suspicious code in graph.py

### ISSUE THREAD

**Issue by prapin** [spacetelescope/spherical_geometry#128]
I found a piece of Python code that doesn't make any sense for me, nor for my colleague, and is probably a bug. 

In class `Graph`, method `_trace_polygons`, sub function `pick_next_edge`, at lines 837 to 844 of `graph.py`:
The `if` branch is always taken since it evaluates two times the exact same Boolean expression, once negated, and then `OR`ed. As far as I can tell, this is equivalent to `if True: return edge`

**Comment by mcara** [comment]
@prapin I concur: this code (the entire `for edge in candidates:` loop) can be omitted in its entirety without affecting the code and indeed it looks _suspicious_.

**Comment by bernie-simon** [comment]
The code is clearly wrong and needs to be modified to match the behavior described at the top of the function. Probably I will modify it to choose the largest difference between the normal vectors, that is, take the dot product between them and choose the smallest one.

**Comment by mcara** [comment]
Fixed via https://github.com/spacetelescope/spherical_geometry/pull/130

**Comment by mcara** [comment]
Fixed via https://github.com/spacetelescope/spherical_geometry/pull/130
