### ISSUE TITLE
Do not make un-anounced changes to API: deprecate first

### ISSUE THREAD

**Issue by mcara** [spacetelescope/spherical_geometry#137]
Since many other packages may rely on `spherical-geometry`, please consider deprecating old API first instead of simply removing it without any grace period.

For example, renaming of [`to_radec()` to `to_lonlat`](https://github.com/spacetelescope/spherical_geometry/pull/81/files?utf8=✓&diff=split#diff-ab7734d820b559d85f732ae44c9207a0L118) was quite sudden. The PR https://github.com/spacetelescope/spherical_geometry/pull/81 suggests that _both_ `to_radec()` _AND_ `to_lonlat` will co-exist. However, while you have linked `SphericalPolygon.to_radec` (now a class attribute) to `SphericalPolygon.to_lonlat()`, you did not do the same for `_SingleSphericalPolygon` class. This resulted in https://github.com/spacetelescope/stsci.skypac/pull/23 breaking `stsci.skypac`.

In addition to using API deprecation, please consider keeping a change log that would announce new features, API changes, and bug fixes in each release. It would be very helpful.

CC: @jhunkeler @stsci-hack

**Comment by mcara** [comment]
Solved via https://github.com/spacetelescope/spherical_geometry/pull/139

**Comment by bernie-simon** [comment]
Wanted to mention that the absence of to_radec is SingleSphericalPolygon was an oversight (a bug) rather than an interface change. It went undetected because that class is usually not called directly.
