### ISSUE TITLE
iter_polygons_flat returns objects of "private" type

### ISSUE THREAD

**Issue by mcara** [spacetelescope/spherical_geometry#138]
`SphericalPolygon.iter_polygons_flat()` returns objects of "private" type `_SingleSphericalPolygon`. If `_SingleSphericalPolygon` is supposed to be "private" (leading underscore), then consider changing the type of the objects returned by `SphericalPolygon.iter_polygons_flat()`.

**Comment by mcara** [comment]
Solved via https://github.com/spacetelescope/spherical_geometry/pull/139

**Comment by bernie-simon** [comment]
In version 1.2.3 you can either use _SingleSphericalPolygon or SingleSphericalPolygon. The latter is preferred.
