### ISSUE TITLE
Repeating points

### ISSUE THREAD

**Issue by rjdverbeek** [spacetelescope/spherical_geometry#158]
When there are repeating points in a dataset of points for a polygon then I get erroneous results for when I try to check if a point is inside or outside the polygon. The workaround is to remove the repeating points.

**Comment by mcara** [comment]
I do not see an issue when only endpoints are the same (closed polygon). Depending on what points are repeated (and where), the polygon may be self-intersecting which is not supported.

**Comment by rjdverbeek** [comment]
Do you have a suggestion to improve the code?

I dont have time to work on this.

Op ma 30 okt. 2023 06:44 schreef Mihai Cara ***@***.***>:
