### ISSUE TITLE
Visual internal compiler error when building spherical-geometry for win x64 python 3.7

### ISSUE THREAD

**Issue by bmatthieu3** [spacetelescope/spherical_geometry#162]
I plan on using spherical-geometry as a dependency of [regions](https://github.com/astropy/regions). You can see the PR [here](https://github.com/astropy/regions/pull/219).

As you can see in this [test](https://ci.appveyor.com/project/Astropy/regions/builds/22538489/job/4mllx1cartggya1l) there is a Visual C++ compiler error when building the wheel of spherical-geometry on a windows x64 arch with python 3.7. However, the wheel for windows x64 python2.7 compiles correctly (see [here](https://ci.appveyor.com/project/Astropy/regions/builds/22538489/job/kaarmxix42vrko57)).
I was wondering if you know what could be the problem or a possible workaround for me to build spherical-geom for winx64 py3.7 ? The AppVeyor yml file used is the following https://github.com/cds-astro/regions/blob/MOC/appveyor.yml . It seems the only thing differentiating the two builds is the python version (the arch used is x64 for both).

I am very looking forward your response as I would not like to remove spherical-geom from astropy/regions dependency (I would like the users to use all the methods without pip installing spherical-geom afterwards when they got an ImportError). Moreover I did not find a python replacement package for spherical-geometry that check if polygons are intersecting on the sphere, compute their area etc...

**Comment by pllim** [comment]
@bmatthieu3 , @sosey suggested that you try updating from VS 14.0 to VS 15 (the 2017 release) and see if that fixes the problem. Thanks!

**Comment by bmatthieu3** [comment]
It fixed the problem. Thank you very much !

**Comment by mcara** [comment]
Thank you @sosey, @pllim
