### ISSUE TITLE
Disagreement re: area

### ISSUE THREAD

**Issue by svw26** [spacetelescope/spherical_geometry#167]
Hello, I thought I'd cross-check the output from `spherical_geometry` with the output from  [`shapely.geometry`](https://pypi.org/project/Shapely/) and I get slightly different numbers.

Method 1:
```python
from spherical_geometry.polygon import SphericalPolygon
lon = [315.4, 308.3, 314.0, 326.4, 315.4]
lat = [18.1, 23.0, 30.0, 30.0, 18.1]
polygon = SphericalPolygon.from_radec(lon, lat)
```
`polygon.area()` outputs 0.030576518412796183 steradians, which converts to 100.376788807 sq deg.

Method 2:
```python
from shapely.geometry import Polygon
points = [(18.1, 315.4), (23.0, 308.3), (30.0, 314.0), (30.0, 326.4), (18.1, 315.4)]  # Latitude specified first
polygon = Polygon(points)
```
In this case, polygon.area outputs 112.595 sq deg.

Please could you let me know what might have been done differently for the two calculations? Or perhaps I've made a mistake myself. The second method doesn't give many significant figures, so perhaps there's some cumulative rounding error somewhere?

Many thanks.

**Comment by mcara** [comment]
The reason for different area values is in that `shapely` performs geometrical computations in a plane while `spherical_geometry` performs them on a sphere. That is, for `shapely` the `lon` and `lat` coordinates are not spherical coordinates but they are interpreted as coordinates in a plane.

For example, let's take a "square" polygon:

```python
from shapely.geometry import Polygon
lon = [315.4, 315.4, 308.3, 308.3, 315.4]
lat = [18.1, 23.0, 23.0, 18.1, 18.1]
polygon = Polygon(zip(lon, lat))
```
Then:
```python
>>> polygon.area
34.78999999999982
```
which is the same as direct area computation in planar geometry:
```python
>>> (315.4-308.3)*(23.0-18.1)
34.78999999999982
```

**Comment by svw26** [comment]
Oh gosh, I thought they'd 'obviously' be using a spherical surface if they take (lon, lat) as input and give square degrees as output! Many thanks for clarifying.
