### ISSUE TITLE
Any way to build with system-installed qd for new version?

### ISSUE THREAD

**Issue by Universebenzene** [spacetelescope/spherical_geometry#181]
For the version before 1.2.11 when spherical_geometry was built with astropy, I can build it with system-installed qd by the `--use-system-qd` or `use-system-libraries` option. While since version 1.2.12, as spherical_geometry doesn't need astropy anymore, those option can't be used again, and `python setup.py build` will automatically use the internal qd-library included in the source. I tried deleting the lines related with qd in the `setup.py` file, and the build passed with the system-installed qt. But when I import the `spherical_geometry.math_util` with this build, an error `undefined symbol: c_qd_add` will occur.

So are there any way to build spherical_geometry with **system-installed qd** for 1.2.12 and new versions?

**Comment by jhunkeler** [comment]
@Universebenzene Let me know if you have any problems building `1.2.16`

**Comment by Universebenzene** [comment]
While this time the build goes fine now. Thanks for the fixing!
