### ISSUE TITLE
Area of polygon with one side on the reference meridian

### ISSUE THREAD

**Issue by JanPolcher** [spacetelescope/spherical_geometry#188]
Hello,
We are having issues with computing the area of a polygon where two segments are along the Greenwich meridian. In our case it is a simple lat/lon quadrilateral with one side sitting on the reference longitude.
```
polyll = [[-0.5, 41.5], [-0.25, 41.5], [0.000000, 41.5], [0.000000, 41.75], [0.000000, 42.0], [-0.25, 42.0], [-0.5, 42.0], [-0.5, 41.75], [-0.5, 41.5]]
centll = [-0.25, 41.75]
sll=polygon.SphericalPolygon.from_lonlat([p[0] for p in polyll], [p[1] for p in polyll], center=centll)
print("Area of polygon defined with Lon & Lat : ", sll.area())
```

The code produces the following error message 

> ERROR (qd_real::acos): Argument out of domain.

and returns a NaN area.

When we displace the two segments slightly from the reference meridian things go back to normal.

**Comment by mcara** [comment]
This is no longer an issue as running this with the latest version of the code I get:
```
Area of polygon defined with Lon & Lat :  5.681530810619506e-05
```

**Comment by mcara** [comment]
This is no longer an issue as running this with the latest version of the code I get:
```
Area of polygon defined with Lon & Lat :  5.681530810619506e-05
```
