### ISSUE TITLE
link to homepage is broken

### ISSUE THREAD

**Issue by falkben** [spacetelescope/spherical_geometry#220]
https://github.com/spacetelescope/spherical_geometry/blob/master/setup.cfg#L22 points to: http://www.stsci.edu/resources/software_hardware/stsci_python

This is the link for the "Homepage" button at https://pypi.org/project/spherical-geometry/

Perhaps should just point to this repo? Or to the docs? https://spacetelescope.github.io/spherical_geometry/spherical_geometry/

**Comment by pllim** [comment]
Fixed in [aafdd4a](https://github.com/spacetelescope/spherical_geometry/commit/aafdd4a58f3e803cf78951a2462ead0fd0a2b705) . Thanks for reporting!
