### ISSUE TITLE
BLD: Stop using oldest-supported-numpy

### ISSUE THREAD

**Issue by pllim** [spacetelescope/spherical_geometry#238]
https://github.com/spacetelescope/spherical_geometry/blob/3be55e127dcf4f8b15d9318b091cd1bc209fdf14/pyproject.toml#L2

Blocks:

* #235 (https://github.com/conda-forge/spherical-geometry-feedstock/pull/30)
* https://github.com/conda-forge/spherical-geometry-feedstock/pull/32

**Comment by pllim** [comment]
Something like this should work but you might also have to drop older Python version.

https://github.com/spacetelescope/synphot_refactor/blob/c14f903729b3e50fa1e1aef5e043c13321b4768c/pyproject.toml#L5

**Comment by pllim** [comment]
If only we still have Joe H around. Woe is us!

**Comment by nden** [comment]
I hope someone will be available soon to address this
