### ISSUE TITLE
A problem with installation under conda (win64, Python 3.12)

### ISSUE THREAD

**Issue by tim-kad** [spacetelescope/spherical_geometry#282]
Here is what I get when trying to install:

```
>conda install conda-forge::spherical-geometry
Channels:
 - defaults
 - conda-forge
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package spherical-geometry-1.0.12-py27_0 requires python 2.7*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ spherical-geometry is not installable because there are no viable options
   ├─ spherical-geometry [1.0.12|1.1.0|...|1.2.5] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which conflicts with any installable versions previously reported;
   ├─ spherical-geometry 1.2.23 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   └─ spherical-geometry 1.2.23 would require
      └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported.
```
Any idea how to fix this?

**Comment by pllim** [comment]
Hi. I have never encountered usage of `::` in the install command before. Maybe it is not grabbing from conda-forge.

What Python version are you using anyway?

Please try this:

`conda install spherical-geometry -c conda-forge`

**Comment by tim-kad** [comment]
Hi,
I just created a clean "test" environment, with Python 3.12.5:

(test) C:\Users\tim-kad>conda install spherical-geometry -c conda-forge
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package spherical-geometry-1.0.12-py27_0 requires python 2.7*, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ spherical-geometry is not installable because there are no viable options
   ├─ spherical-geometry [1.0.12|1.1.0|...|1.2.5] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which conflicts with any installable versions previously reported;
   ├─ spherical-geometry 1.2.23 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   └─ spherical-geometry 1.2.23 would require
      └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported.

**Comment by pllim** [comment]
Maybe due to https://github.com/conda-forge/spherical-geometry-feedstock/issues/33 ? `python >=3.11,<3.12.0a0` is definitely a problem. Is this something you can fix, @jhunkeler and @mcara ?

@tim-kad , are you able to try with Python 3.11?

**Comment by tim-kad** [comment]
Yes, with 3.11.10 it installed just fine, thanks!
It would be fantastic if it worked for 3.12 too.

**Comment by pllim** [comment]
I think https://github.com/conda-forge/spherical-geometry-feedstock/pull/40 would fix this
