### ISSUE TITLE
Import error in Python 3.5

### ISSUE THREAD

**Issue by mcara** [spacetelescope/spherical_geometry#98]
@bernie-simon When I try to run @felixveysseyre code from https://github.com/spacetelescope/sphere/issues/97#issuecomment-313528288 I get the following error under Python 3.5 env:
```python
/Users/.../sphere/spherical_geometry/graph.py in <module>()
     19 # LOCAL
     20 from . import great_circle_arc
---> 21 from . import math_util
     22 from . import vector
     23 

ImportError: cannot import name 'math_util'
```

**Comment by pllim** [comment]
math_util is a C-extension

**Comment by pllim** [comment]
Was your C-extension ever compiled properly? Did you see any error when you installed it?

**Comment by pllim** [comment]
I cannot reproduce your import error in Python 3.5.3. I did a `conda install sphere` from the "astroconda" channel.
```
$ ipython
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from spherical_geometry.polygon import SphericalPolygon

In [2]: 
```

**Comment by pllim** [comment]
Travis CI does not report any error on Python 3.5. So, this is probably something messed up on your side.

**Comment by mcara** [comment]
@pllim quite possibly...
